README.md, sertop.el
Thanks for SerAPI; it's really neat.
This little Emacs mode makes it easier to play with sertop; it runs it and pretty-prints responses, with syntax highlighting.
=> Add a small Emacs REPL for sertop

serlib/ser_stdarg.ml
Fixes #66.
I was lazy doing this as 8.9 does indeed move these genargs.
=> [serlib] Add serializers for `constr_with_bindings` genarg.

tests/genarg/dune, tests/genarg/fix.v
The `fix` tactic with argument is used in proofs in some projects, e.g., [Binary Rational Numbers](https://github.com/coq-community/qarith-stern-brocot). It currently gives an error as in #68.
Should probably not be merged until build passes.
=> [serlib] add test for fix tactic

tests/genarg/dune, tests/genarg/functional_scheme.v, tests/genarg/rename.v
I found two more more problems with `sercomp`: `Functional Scheme` (from the `FunInd` module) and the `rename` tactic.
Dune tests are added but commented out for now.
=> Test for Functional Scheme and rename tactic

tests/genarg/dune, tests/genarg/hint_rewrite.v
I get errors when serializing occurrences of `Hint Rewrite`. Here is a test for that in the conventional way.
=> [serlib] add test for Hint Rewrite

tests/genarg/add_field.v, tests/genarg/dune
Here is a test for the `Add Field` command, which gives errors related to `field_mods` arguments.
=> [serlib] test for Add Field

tests/genarg/dune, tests/genarg/intropattern.v
Yet another test, this time for "intro patterns", e.g., `ipattern:(H)`. They cause argument errors.
=> [test] add test for intropatterns

CHANGES.md, sertop/compser.ml, sertop/dune, tests/genarg/dune, tests/genarg/tactic_notation.v
Here is a PR that's not necessarily meant to be merged. The primary purpose is to demonstrate the deserialization `Anomaly` errors we are getting in some projects (currently: TLC, stdpp, Binary Rational Numbers).
This branch rebases the current `v8.9` on the `v8.9+sercomp_mode` branch to get the `sercomp` updates. I then added a deserialization program `compser` based on this `sercomp`.
Here is how to reproduce the error from the smallest example I could construct.
```shell
$ sercomp --mode=sexp tests/genarg/tactic_notation.v > tactic_notation.sexp
$ compser --mode=sexp tactic_notation.sexp
```
The output is a bunch of sexps and then the following:
```
compser: internal error, uncaught exception:
"Anomaly: Unknown tactic alias: SerComp.dup_#_2C9A39DD."
```
Note that this is when parsing …
=> [serlib] compser tool with failed deserialization example

CHANGES.md, serapi/serapi_paths.ml, serapi/serapi_paths.mli, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, serlib/ser_mltop.ml, sertop/complib.ml, sertop/complib.mli, sertop/compser.ml, sertop/sercomp.ml, sertop/sertop.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_init.ml, sertop/sertop_ser.ml, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
The protocol now supports a method:
```lisp
(NewDoc ((top_name "Module")
(iload_path (path_1 ... path_n)
(require_libs (require_1 ... require_n))))
```
where `path_i` is of type
```ocaml
Mltop.coq_path = {
path_spec: coq_path_spec;
recursive: bool;
}
type coq_path_spec =
| VoPath of vo_path_spec
| MlPath of string
type vo_path_spec = {
unix_path : string;
coq_path  : Names.DirPath.t;
implicit  : bool;
has_ml    : add_ml;
}
```
and `require_i` is of type:
```ocaml
string * string option * bool option
```
where `(module, root, import)` corresponds to `From root Require import module`
`iload_path` and `require_libs` are optional, if absent, SerAPI will
resort to the defaults.
By default, invoking `sertop` will create a document with the standard
paths and `Prelude` loaded. To avoid that, use …
=> [serapi] Add document creation `NewDoc` protocol call.

CHANGES.md, sertop/sertop_sexp.ml, tests/genarg/dune, tests/genarg/test_roundtrip
Following #69, which fixed the round trip for the batch compiler cases, we modify the test cases so we test the full serialization / deserialization roundtrip.
=> [sertop] Set Coq module name correctly from module file.

tests/genarg/dune, tests/genarg/instantiate.v
Yet another missing tactic argument witness bug, it seems. This time for the `instantiate` tactic.
Another thing I noticed while investigating this is that `sercomp` does not propagate exceptions to the shell level unless one uses `--mode=sexp`. For example, the following does not raise any exception:
```shell
$ sercomp.exe --exn_on_opaque tests/genarg/instantiate.v
$ echo $?
0
```
On the other hand:
```shell
$ sercomp.exe --mode=sexp --exn_on_opaque tests/genarg/instantiate.v
...
Error: Serlib Error: [raw: (ExtraArg lglob): ABSTRACT]
$ echo $?
1
```
=> [test] Add test for instantiate tactic

CHANGES.md, sertop/complib.ml, sertop/complib.mli, sertop/compser.ml, sertop/sercomp.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, tests/genarg/dune
This way we can do `.sexp -> .vo`.
=> [sertop] Add `--mode=vo` option that will output a `.vo` file.

tests/genarg/dune, tests/genarg/setoid_rewrite.v
We found another non-ssreflect tactic that causes parsing errors: `setoid_rewrite`. Here is a minimal test case that reproduces the problem (note that the `at 1` is the trigger).
=> [test] Add test for setoid_rewrite tactic

tests/genarg/assoc.v, tests/genarg/dune
Here is an example file where, strangely, `coqc` and `sercomp`/`compser` differ in whether a proof fails. With `coqc`, I get:
```shell
File "./assoc.v", line 81, characters 6-31:
Error: No such goal.
```
That is, the proof of the lemma `get_del_same` fails.
However, `sercomp` and `compser` produce a `.sexp` file and then a `.vo` file without complaints. But now something really strange happens. If I remove the last lemma (`get_set_diff_default`) suddenly `get_del_same` starts to fail with `sercomp` at the right place.
I have no idea what's going on here. Any tips on debugging more would be welcome.
=> [test] Add test case showing discrepancy between coqc and sercomp/compser

CHANGES.md, sertop/sercomp_lib.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli
We sometimes need to check sexprialized files but have no use for the `.vo` output (which can be quite large and costly to produce). This PR introduces a `check` mode that does what the `vo` mode does but without building/writing the `.vo` file. Seems complementary to any improvements in the `parse` mode.
=> [sercomp] Add check mode for compser

CHANGES.md, sertop/sercomp_lib.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, tests/quick/ab.v, tests/quick/assoc.v, tests/quick/dune
IMHO this is not an option we want to support in the long term as
proposed here, however @palmskog proposed it and indeed it may be very
useful in the short term.
=> [sercomp] Add experimental `--quick` option to skip proofs.

CHANGES.md, sertop/sercomp_lib.ml, sertop/sertop.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_init.ml, sertop/sertop_init.mli
We want to experiment with several forms of parallel checking, and this means that controlling the maximum number of parallel workers/threads/jobs (when using `--async=...`) is a must. I tried to only do edits to remove the hardcoding and preserve the default. I'd be fine with this living in a separate branch for now, though.
=> [sercomp] Add --async-workers option to set max parallel jobs

sertop/compser.ml, sertop/sercomp.ml, sertop/sercomp_lib.ml, sertop/sercomp_lib.mli
Very basic description of the one key modes of use of `sercom` and `compser` to begin addressing #98.
=> [doc] Add man pages with examples for sercomp and compser

sertop/sercomp_lib.ml
This check is supposed to be used only when in non-quick mode, so for
now it is safe to disable, as 8.10 does.
A more throughout analysis is needed tho.
=> [sercomp] Disable kernel safety check when in --quick mode.

tests/async/dune, tests/async/quote.v
After the switch to dynamic plugin loading, we are seeing errors like the following with the `--async` option:
```
Error:
while loading quote_plugin.cmxs:
cannot find file /home/test/src/project/quote_plugin.cmxs in search path
```
where `/home/test/src/project` is the directory we are running `sercomp` or `compser` from. 
Here is a test that replicates this error in a minimal example, at least for me locally. Note that running `dune install` or not makes no difference.
To speculate a bit, this may have do with async workers not getting the right `OCAMLPATH` variable.
=> [test] Add async test

sertop/sertop_init.ml, sertop/sertop_loader.ml
As observed in https://github.com/ejgallego/coq-serapi/pull/106, mltop upstream makes impossible to use a custom loader with workers.
We have added a workaround in the `v8.9+serapi` branch, however we
must adapt our loader to receive the full path.
=> [sertop] Adapt to mltop passing the full module path.

.travis.yml
This allows Coq to be cached, and it is more faithful to what most
users do.
=> [ci] [travis] Update Travis to use Coq's OPAM package.

Makefile
This should allow Nix users to use the `Makefile` stub.
=> [build] Don't overwrite `OCAMLPATH` but append to it.

README.md
This fixes a bunch of typos/grammar, and flags up `sercomp` more clearly.
=> [doc] Revise README.md to fix typos and omissions.

AUTHORS, CHANGES.md, serlib/ser_cEphemeron.ml, serlib/ser_cMap.ml, serlib/ser_cMap.mli, serlib/ser_cemitcodes.ml, serlib/ser_cemitcodes.mli, serlib/ser_declarations.ml, serlib/ser_declarations.mli, serlib/ser_environ.ml, serlib/ser_mod_subst.ml, serlib/ser_mod_subst.mli, serlib/ser_names.ml, serlib/ser_names.mli, serlib/ser_opaqueproof.mli, serlib/ser_retroknowledge.ml, serlib/ser_retroknowledge.mli
Hi,
This is what I have for serializing the `Env`. It relies on exposing `type globals` in kernel/environ.mli. 
To reduce the output size, I simply omit the modules and module types in Env (see `sexp_of_globals` in ser_environ.ml),  but there may be a better way to do that.
=> [serlib] add partial support for serializing Env

tests/quick/dune, tests/quick/ordered.v, tests/quick/reserved.v
Here are two tests that give the following error when given to `sercomp` with `--quick`:
```
Error: 
Anomaly
"True Future.t were created for opaque constants even if -async-proofs is off"
Please report at http://coq.inria.fr/bugs/.
``` 
Note that `Proof.` or `Proof using.` makes no difference, but I used the latter for completeness.
=> [test] Add two failing tests for --quick

CHANGES.md, serapi/serapi_protocol.ml
After discussion in #124 and on Gitter, indeed it makes sense every
command is terminated with `Completed`, even those raising.
This was already the case of `Add`, now hopefully all of them should
behave this way.
Closes #124
=> [serapi] Make sure every command ends with `Completed`

CHANGES.md, serlib/ser_cemitcodes.ml, serlib/ser_cemitcodes.mli, serlib/ser_declarations.mli, serlib/ser_entries.ml, serlib/ser_names.ml, serlib/ser_names.mli, serlib/ser_safe_typing.ml, serlib/ser_safe_typing.mli
Side effects in the GADT where tricky to encode due to limitations of
the serializers.
Anyways, ppx_sexp_conv is doing something strange in the `sexp_of`
case for the `global_declaration` GADT; I had to manually code the
serializer, but it should work a bit better IMO.
=> [serlib] Fix serialization for global_declaration

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, sertop/sertop_ser.ml
We now output the location of tokens in the input stream, and provide
sercomp with the ability to tokenize.
@palmskog I will add a sercomp tokenization mode soon.
=> [serapi] Output location on tokenization.

.travis.yml, CHANGES.md, coq-serapi.opam, serlib/ser_constrexpr.ml, serlib/ser_environ.ml, serlib/ser_genintern.ml, serlib/ser_glob_term.ml, serlib/ser_glob_term.mli, serlib/ser_stdlib.ml, serlib/ser_univ.ml
After 4.05.0 we have to provide qualified serializers for core OCaml
types such as `ref` or `Lazy.t`; not worth supporting 4.06.0 anymore
on the 0.7.0 series.
=> [build] Drop support for OCaml 4.06.0

.travis.yml, CHANGES.md, coq-serapi.opam, serlib/dune, serlib/serType.ml, serlib/ser_cSet.ml, serlib/ser_cSet.mli, serlib/ser_constr.ml, serlib/ser_constr.mli, serlib/ser_context.ml, serlib/ser_context.mli, serlib/ser_evar.ml, serlib/ser_evar.mli, serlib/ser_names.ml, serlib/ser_names.mli, serlib/ser_sorts.ml, serlib/ser_sorts.mli, serlib/ser_stdlib.ml, serlib/ser_uint63.ml, serlib/ser_univ.ml, serlib/ser_univ.mli
This is a bit cumbersome but I think it will be useful to many people.
For now we only support JSON (de) serialization of kernel terms.
Next steps:
- AST terms
- sercomp mode
=> [serlib] (Partial) support for Yojson serialization

CHANGES.md, sertop/sertop_init.ml
Indices matter is `false` by default in coqc/coqtop, however if unset
the kernel defaults to a more restrictive default of `true`.
For compatibility we follow `coqc` and set it to `false` too.
Note that this seems like the only discrepancy.
Closes #157
=> [coq_init] Set `indices_matter` to false, as default in Coq.

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, sertop/sertop_ser.ml
This should improve #162 ; note that unfortunately some error wrapping
is still happening upstream so the usefulness of fine-grained `CoqExn`
is not the best yet (cc: coq/coq#9686)
=> [serapi] Pretty-print exceptions inside `CoqExn` answer.

serapi/dune, sertop/dune
This PR proposes to install the currently private serapi and sertop sub-libraries, to facilitate the development of out-of-tree programs similar to sertop/sercomp.
As suggested by @ejgallego , the public library names are timestamped with the version, to indicate that the API is unstable.
If this gets merged I plan on submitting a similar PR for the 8.9 branch, that I'm currently using.
=> Install the serapi and sertop sub-libraries

.travis.yml, coq-serapi.opam, serlib/plugins/ltac/ser_tacentries.ml, serlib/plugins/ltac/ser_tacenv.ml, serlib/plugins/ssr/ser_ssrast.ml, serlib/plugins/ssr/ser_ssrequality.ml, serlib/plugins/ssr/wrap_ssrast.ml
This is necessary when Coq is compiled with the standard Makefile.
In order to have a solution that both works with `-pack` and Dune
mode, we need to wrap the mli-only file that Coq is shipping upstream
due to differences in linking.
Fixes #143
We also update the Travis setup so we test both OPAM and the Dune build.
Proper working did require patching Coq's upstream META file so the plugin loader works correctly, c.f. https://github.com/coq/coq/pull/10943 https://github.com/ocaml/opam-repository/pull/15103
=> [serlib] Fix ppx_import w.r.t. old-style pack plugin compilation

README.md, coq-serapi.opam
Here are some metadata and documentation fixes and additions to prepare for the 0.7.0 release. I'm open to discussion about specifics, e.g., maybe the `coq-serapi.opam` file is supposed to be auto-generated? In any case, the added stuff could then be transferred into dune files.
=> [doc] Metadata and documentation additions

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, serlib/ser_feedback.mli, sertop/sertop_async.ml, sertop/sertop_ser.ml, sertop/sertop_sexp.ml, sertop/sertop_util.ml, sertop/sertop_util.mli
This way clients don't need to do a round-trip to convert the `Pp.t`
to a string.
Closes #184 , closes #162.
=> [serapi] Add string formatted messages to `CoqExn` and `Message`

CHANGES.md, FAQ.md, README.md, notes/build.md, serapi/dune, serlib/plugins/extraction/dune, serlib/plugins/firstorder/dune, serlib/plugins/funind/dune, serlib/plugins/funind/ser_g_indfun.ml, serlib/plugins/ltac/dune, serlib/plugins/setoid_ring/dune, serlib/plugins/setoid_ring/ser_g_newring.ml, serlib/plugins/ssr/dune, serlib/plugins/ssr/ser_ssrast.ml, serlib/plugins/ssr/ser_ssrequality.ml, serlib/plugins/ssr/ser_ssrparser.ml, serlib/plugins/ssrmatching/dune, sertop/dune, sertop/sercomp.ml, sertop/sertok.ml, sertop/sertop_async.ml, sertop/sertop_bin.ml, sertop/sertop_ser.ml, sertop/sertop_ser.mli, sertop/sertop_sexp.ml, sertop/sertop_util.ml, sertop/sertop_util.mli
We now build the OCaml libraries by default; this may allow us to drop
annoying `Serapi_` prefix from module names.
=> [serapi] [general] Bump version numbers for 8.11 and wrap libraries

AUTHORS, CHANGES.md, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_bin.ml, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
the effect is equivalent to coqtop option -topfile
if --topfile <filename> is present, the top name is set as if <filename> is compiled,
otherwise the top name is (SerTop)
=> added sertop option --topfile <filename>

CHANGES.md, sertop/sercomp.ml, sertop/sertok.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_async.mli, sertop/sertop_bin.ml, sertop/sertop_init.ml, sertop/sertop_init.mli, sertop/sertop_js.ml, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
in agreement with upstream coq v8.11 as per discussion
https://github.com/ejgallego/coq-serapi/issues/198
with the option  --disallow-sprop that sets allow-sprop false
and thus forbids using the proof irrelevant SProp sort
=> * set allow-sprop true by default at the init of coq 

CHANGES.md, coq-serapi.opam
PR #194 was actually incorrect, deprecations of alias types seem to
have happened in ppx_sexp_conv v0.13 , thus SerAPI was broken in v0.12
after it.
=> [build] Bump minimum sexplib version to v0.13

CHANGES.md, sertop/sercomp.ml, sertop/sertok.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_bin.ml, sertop/sertop_init.ml, sertop/sertop_init.mli
Error recovery is now off by default. This seems to be more in line
with what users do expect. Fixes #201
=> [serapi] New option `--error-recovery` to enable error recovery.

sertop/sertop_sexp.ml
the purpose of --topfile option is to set the top name while the remaining behaviour is expected to be the same
this patch mirror upstream and uses Stm.TopPhysical filename when --topfile filename is present; 
in particular command (Query () Goals) behaves consistent with interactive mode
=> coqtop --topfile will create document using Stm.Interactive and not Stm.VoDoc

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli
This doesn't fully provide a solution for the problem of comments
being ignored by SerAPI, but at least users can now workaround that by
getting all the comments and properly splicing them.
Provides a workaround / improves #191, #200 .
We defer further discussion to the upstream issue
https://github.com/coq/coq/issues/12413
=> [serapi] New query `Comments` to return all comments in a document

serapi/serapi_goals.ml
Avoids exception by passing `~abort_on_undefined_evars:false`.
Fixes #228.
=> Allow printing goals with evars

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli
Coq's library handling code contains an API to map "logical" paths to
"physical" paths and vice-versa, we provide a helper query
```lisp
(Query () (LogicalPath file))
```
which exposes this resolution for users, as requested in
https://github.com/cpitclaudel/alectryon/pull/25
Note that the plan for 8.14 is to expose the fully principled API that
will be introduced at https://github.com/coq/coq/pull/14059.
=> [serapi] New query `(Query () (LogicalPath file))`

CHANGES.md, serapi/serapi_doc.ml, serapi/serapi_doc.mli, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, sertop/sertop_async.ml, sertop/sertop_ser.ml, sertop/sertop_sexp.ml
We introduce a new commmand:
```lisp
(SaveDoc opts)
```
to save .vo files from an interactive session. `opts` are optional,
and can be
- `(sid s)`: save the document at a specific sentence
- `(prefix_output_dir dir)` add a prefix to the `file.vo` to be saved.
Note that Coq requires that the module name and the filename do match,
thus in order to use this command `sertop` must be called with the
`--topfile file.v` flag, otherwise `CannotSaveVo` will be raised.
Closes #128 #238
=> [serapi] New command `SaveDoc` to save .vo files.

sertop/sertop_loader.ml
As witnessed in #241, the current error is confusing, we try to
improve it as this is a common problem with SerAPI's install.
=> [sertop] Improve error message when sertop fails to locate a plugin

serlib/ser_names.ml, serlib/ser_names.mli
* Label, MBId, and ModPath already had yojson but were missing the type annotation in the interface.
* KerName did not have yojson serialization but one was easy to add.
=> Some missing yojson annotations

README.md
=> [doc] Add Nix instructions.

CHANGES.md, serlib/ser_environ.ml, serlib/ser_environ.mli, serlib/ser_pretype_errors.ml, serlib/serlib_base.mli, serlib/serlib_init.ml, serlib/serlib_init.mli, sertop/sercomp.ml, sertop/sername.ml, sertop/sertok.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_bin.ml
Should fix #250, tho it is far from a principled solution.
Several Coq structures do like to embed a full `env`; what we do here,
it is far from practical, as it won't scale, but at least should
alleviate the immediate pain
Other possible hack would to add an `--omit_env` parameter that would
turn all `env` into abstract; but generally, we should really
introduce a mechanism for the management of contextual info as
discussed in the bug tracker.
=> [serlib] Ignore `env` parameter in certain exceptions

CHANGES.md, sertop/sertop_arg.ml
The command line argument variable still has precedence.
=> [sertop] Understand COQLIB variable to set --coqlib

CHANGES.md, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, sertop/sertop_ser.ml
Now users can do
```
(Parse (entry Constr) $text)
```
to parse normal expressions. By default, `Parse` is still bound to the parsing entry for a top level vernacular command.
Fixes #272
=> [serapi] Allow to parse different entries (expressions added)

CHANGES.md, sertop/sercomp.ml, sertop/sername.ml, sertop/sertok.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_async.mli, sertop/sertop_bin.ml, sertop/sertop_init.ml, sertop/sertop_init.mli, sertop/sertop_js.ml, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
Addresses https://github.com/ejgallego/coq-serapi/issues/287 for Coq 8.14 
This is the backport of https://github.com/ejgallego/coq-serapi to branch 8.14
=> Add the --impredicative-set option

serlib/plugins/cc/dune, serlib/plugins/micromega/dune, serlib/plugins/syntax/dune, serlib/plugins/syntax/ser_g_number_syntax.ml, serlib/plugins/syntax/ser_number.ml, serlib/plugins/tauto/dune, serlib/plugins/zify/dune, serlib/ser_constrexpr.ml, serlib/ser_constrexpr.mli, serlib/ser_notation.ml, serlib/ser_notation.mli, serlib/ser_numTok.ml, sertop/sertop_loader.ml
=> [serlib] Support a few more plugins from Coq's stdlib.

sertop/sertop_init.ml
It is not actually needed and will go away in https://github.com/coq/coq/pull/17069
=> Don't call init_known_plugins

serlib/ser_constrexpr.ml, serlib/ser_constrexpr.mli, serlib/ser_extend.ml, serlib/ser_extend.mli, serlib/ser_notation.ml, serlib/ser_notation.mli, serlib/ser_notation_gram.ml, serlib/ser_notationextern.ml, serlib/ser_notationextern.mli
This is a partial adaptation of coq/coq#17117 to serapi but I failed to complete it. I seem to meet the ml/mli problem: `type side` is in `constrexpr.ml` (no `constrexpr.mli`) and
```ocaml
type side =
[%import: Constrexpr.side] 
[@@deriving sexp,yojson,hash,compare]
```
fails with `Error: Unbound type constructor Constrexpr.side`.
Is there some incantation I should use? Or move `side` in a file that has an `mli`?
=> Adapt to #17117: level is now in notationterm.ml, side in constrexpr.ml

CHANGES.md, serlib/plugins/ltac2/ser_tac2expr.ml
This was due to missing constructor. Thanks to @quarkcool for the report.
=> [serlib] Fix ltac2 plugin wrong piercing

serlib/ser_notation_term.ml, serlib/ser_notation_term.mli
I guess I made the canonical fix?
To be merged synchronously with coq/coq#17827
=> Adapt to #17827: new type Notation_term.notation_var_binders

serapi/serapi_protocol.ml
The Coq PR is to fix #17963: sigma has to be passed to search functions.
It has to be merged synchronously with https://github.com/coq/coq/issues/17987.
=> Adapt to Coq PR #17987 which adds sigma to the API of search functions

tests/genarg/functional_induction.v, tests/genarg/mbid.v, tests/genarg/setoid_rewrite.v
This is to address https://github.com/coq/coq/pull/18164
=> remove all references to deprecated Arith modules from genarg tests

serlib/plugins/ltac/ser_rewrite.ml, serlib/plugins/ltac/ser_rewrite.mli, serlib/plugins/ltac/ser_tacarg.ml
The type constructor `Rewrite.strategy_ast` now expects 3 arguments (the third one is for bound fixpoint identifiers).
To be merged synchronously with coq/coq#18094
=> Adapt to coq/coq#18094: rewrite strategies: fix

serlib/ser_declarations.ml
This is to be merged synchronously with coq/coq#18229.
=> Adapt to #18229: nested_type is now recarg_type (no more "nested" mark)

serlib/plugins/extraction/ser_g_extraction.ml, serlib/plugins/funind/ser_g_indfun.ml, serlib/plugins/ltac/ser_tacarg.ml, serlib/plugins/ltac2/ser_g_ltac2.ml, serlib/plugins/ring/ser_g_ring.ml, serlib/plugins/syntax/ser_g_number_syntax.ml, serlib/ser_genarg.ml, serlib/ser_genarg.mli
(and extraction uses vernac arg extend instead of full arg extend)
=> Adapt to coq/coq#18719 (stricter type for vernac_argument extend)

.github/workflows/ci.yml, CHANGES.md, coq-serapi.opam, tests/genarg/move.v
Fixes #399
This means we can enable `@with-test` in the opam file!
=> [test] Don't require math-comp to run the test suite.

.github/workflows/ci.yml, coq-serapi.opam
We also remove the old !pinned method, as the setup-ocaml action does pin Coq in all cases.
Fixes #208
=> [ci] Rework CI as to be more modular

CHANGES.md, serlib/ser_constrexpr.mli, serlib/ser_dAst.ml, serlib/ser_deprecation.ml, serlib/ser_feedback.mli, serlib/ser_genredexpr.ml, serlib/ser_genredexpr.mli, serlib/ser_glob_term.mli, serlib/ser_goptions.ml, serlib/ser_goptions.mli, serlib/ser_pp.ml, serlib/ser_pp.mli, serlib/ser_xml_datatype.mli
This was a long overdue TODO.
cc: https://github.com/ocaml/opam-repository/pull/25951
=> [serlib] Don't use compat type Result.result

.github/workflows/ci.yml
Otherwise we risk the Coq local build to be inconsistent.
=> [ci] Build Coq after final OPAM setup.
