ejgallego/coq-serapi

README.md
=> Add Coq8.6 link

CHANGELOG.md, sertop/sercomp.ml, sertop/sertop.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli
In case this is just the feature you want to fix, this works well for me.
=> exposing -I in sertop, fixes #53

CHANGES.md, sertop/sercomp.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli
This is very preliminary but should help with #76.
=> [sercomp] Add option controlling output mode.

tests/genarg/dune, tests/genarg/functional_induction.v
This appears to be the only problem before the QuickSort Complexity Coq-contrib project works.
=> [test] Add test for functional induction tactic

CHANGES.md, serapi/serapi_assumptions.ml, serapi/serapi_assumptions.mli, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, serlib/ser_printer.ml, sertop/sertop_ser.ml
This is work-in-progress to add an `(Assumptions id)` query.
=> [serapi] Add `Assumptions` query.

tests/genarg/abstract.v, tests/genarg/dune
This appears to be the last error when serializing/deserializing the Binary Rational Numbers Coq-contrib project.
=> [test] Add test for abstract tactic

coq-serapi.opam
Also, emphasize the use as a library a bit more in synopsis.
=> [build] Update opam file with ocamlfind dependency

CHANGES.md, serlib/plugins/ltac/ser_tacarg.mli, serlib/plugins/ssr/dune, serlib/plugins/ssr/ser_ssrast.ml, serlib/plugins/ssr/ser_ssrparser.ml, serlib/plugins/ssrmatching/dune, serlib/plugins/ssrmatching/ser_ssrmatching.ml, serlib/ser_genarg.mli, sertop/sertop_loader.ml, tests/genarg/dune, tests/genarg/move.v
This requires a patch to Coq upstream, so it will have to wait for merge of
- https://github.com/coq/coq/pull/9557
For the 8.9 version see #73
=> [serlib] Fix serialization of ssr expressions (cc #68)

CHANGES.md, serlib/ser_future.ml, serlib/ser_mod_subst.ml, serlib/ser_mod_subst.mli, serlib/ser_names.ml, serlib/ser_names.mli, serlib/ser_opaqueproof.ml
This is mildly useful as to inspect proofs.
=> [serlib] Serialize Opaqueproof.opaque

.travis.yml, CHANGES.md, serlib/serType.ml, serlib/ser_cMap.mli, serlib/ser_cSet.ml, serlib/ser_cSet.mli, serlib/ser_cooking.ml, serlib/ser_cooking.mli, serlib/ser_entries.ml, serlib/ser_evar.ml, serlib/ser_names.ml, serlib/ser_names.mli, serlib/ser_opaqueproof.ml, serlib/ser_opaqueproof.mli, serlib/ser_safe_typing.ml, serlib/ser_safe_typing.mli, serlib/ser_univ.ml, serlib/ser_univ.mli
This is in preparation of #129 and Json support.
=> [serlib] Improve interfaces + serialize kernel entries.

CHANGES.md, serlib/ser_declarations.ml, serlib/ser_declarations.mli, serlib/ser_entries.ml, serlib/ser_rtree.ml, serlib/ser_univ.ml, sertop/sercomp.ml, sertop/sertop_init.ml
Fixes from #129 and @palmskog tests.
=> [serlib] Miscellaneous fixes for serializers

notes/announce-0.6.md
@palmskog do you mind having a look?
=> [doc] Release 0.6.1

README.md, notes/announce-0.6.md
Here is another pass over documentation with fixes (e.g., for consistency) and some small additions.
=> Fixes to README.md and 0.6 announcement

.travis.yml, coq-serapi.opam
Should make the failure in #143 more explicit.
=> [opam] Improve OPAM bounds.

CHANGES.md, Makefile, serapi/serapi_goals.ml, serapi/serapi_goals.mli, sertop/sertop_ser.ml
=> [serapi] [goals] Print goal name if available.

serlib/ser_feedback.ml, serlib/ser_feedback.mli, serlib/ser_goptions.ml, serlib/ser_goptions.mli, serlib/ser_libnames.ml, serlib/ser_libnames.mli, serlib/ser_pp.ml, serlib/ser_pp.mli, serlib/ser_stateid.ml, serlib/ser_stateid.mli, serlib/ser_xml_datatype.ml, serlib/ser_xml_datatype.mli
This is what JsCoq needs in order to serialize all its protocol.
=> [serlib] More Json support.

CHANGES.md, serlib/ser_names.ml
Closes #167, thanks to @corwin-of-amber for the report!
=> [serlib] Fix capitalization conventions for a few types in `Names`

.travis.yml
Thanks to all the people who sorted the situation out on the OPAM side.
=> [ci] Remove hacks now that ppx_deriving_yojson 3.4 is on OPAM.

CHANGES.md, serapi/serapi_goals.ml, serapi/serapi_goals.mli
This is an import of the changes in
https://github.com/ejgallego/jscoq/commit/300b1923197f31b8e90226a3f3d23bda6ea65be6
=> [serapi] Add bullet suggestion information to goals

CHANGES.md, sertop/sertop.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
=> [sertop] Add `--no_prelude` option

README.md
Also, some small formulation improvements.
=> [doc] Mention new SerAPI applications in README.md

CHANGES.md, Makefile, README.md, serapi/serapi_goals.ml, serapi/serapi_protocol.ml, serapi/serapi_protocol.mli, serlib/ser_names.ml, sertop/sertop_ser.ml, tests/genarg/dune, tests/genarg/mbid.v
=> [serlib] [serapi] Fix serialization of `MBId`, improve printing state.

CHANGES.md, README.md, sertop/dune, sertop/sertok.ml, sertop/sertop_ser.ml, sertop/sertop_ser.mli
This is rudimentary but may at least convey the general idea of what we need in terms of batch tokenization.
There are two fundamental problems right now that I don't know how to solve due to lack of API knowledge:
1. how to get the raw string from a sentence read from a stream
2. how to get serialization to print the locs as in `sertop`
Could you take a look and give some pointers @ejgallego?
=> [sercomp] sertok program for batch tokenization

README.md, notes/build.md
Some more minor documentation stuff to prepare for 0.7.0.
=> [doc] Small README fixes and build instruction updates

FAQ.md
Close #109 , instead of summarizing the discussion in the FAQ we just
point out to it, IMO it is of very good quality.
=> [doc] Update FAQ.

CHANGES.md, FAQ.md, notes/announce-0.7.0.md
=> [doc] Release 0.7.0 announcement

README.md
Also fixed some previous links.
=> [doc] Update README.md with additional clients of SerAPI

CHANGES.md, Makefile, coq-serapi.opam, dune-project, sertop/dune, tests/fail/dune, tests/genarg/dune, tests/quick/dune, tests/sername/dune
This way we can use newer actions very convenient for tests.
=> [build] Require Dune >= 2.0

CHANGES.md, serapi/serapi_protocol.ml
=> [serapi] Fix missing newline to separate goals

FAQ.md
=> [doc] [faq] Comment on sexps oddities.

LICENSE, jscoq/coq-js/jslib.ml, jscoq/coq-js/jslib.mli
We clarify and fix some problems identified in #266, tho these are minor (other than bad writing) as LGPL-2.1+ as used by Coq already allows to consider code to be GPL-3+ if desired.
Fixes #266
=> [license] Clarify and fix a few typos.

serlib/ser_constrexpr.ml, serlib/ser_constrexpr.mli, serlib/ser_notationextern.ml, serlib/ser_notationextern.mli, serlib/ser_vernacexpr.ml, serlib/ser_vernacexpr.mli
Adapt to https://github.com/coq/coq/pull/12324
I only made things compile so as to make Coq CI green, there might be more to be done later.
=> Adapt to coq/coq#12324

CHANGES.md, sertop/comp_common.ml, sertop/comp_common.mli, sertop/sercomp.ml, sertop/sername.ml, sertop/sertok.ml, sertop/sertop_arg.ml, sertop/sertop_arg.mli, sertop/sertop_async.ml, sertop/sertop_async.mli, sertop/sertop_bin.ml, sertop/sertop_init.ml, sertop/sertop_init.mli, sertop/sertop_js.ml, sertop/sertop_sexp.ml, sertop/sertop_sexp.mli
Closes https://github.com/ejgallego/coq-serapi/issues/287
=> Add support for the -impredicative-set option

tests/genarg/libTactics.v
This should be backwards compatible.
=> Adapt w.r.t. coq/coq#16904.

.github/workflows/ci.yml, coq-serapi.opam, dune
This is towards making a prerelease tag compatible with Coq 8.17+rc1.
=> adjust opam, dune, ci for 8.17+rc1

tests/genarg/libTactics.v
Should be backwards compatible.
=> Adapt w.r.t. coq/coq#16910.

sertop/sername.ml
=> Adapt to coq/coq#17096 (detype isgoal argument is optional)

serapi/serapi_goals.ml
=> Adapt w.r.t. coq/coq#17170.

serlib/ser_extend.ml, serlib/ser_notation_term.ml, serlib/ser_notation_term.mli
Straightforward adaptation to coq/coq#16937.
=> Adapting to PR #16937 (that fixes recursive notation bug #12467).

README.md
Thanks to everyone that helped and used this project for almost 7 years!
The following issues are solved by coq-lsp:
closes #252, closes #261, closes #234, closes #202, closes #117,
closes #49, closes #32, closes #26, closes #24, closes #21,
closes #18, closes #13
=> [meta] Put SerAPI in maintenance mode.

CHANGES.md, serlib/plugins/ltac/ser_tacarg.ml, serlib/ser_genarg.ml
This is a quick fix, but should work for now.
=> [serlib] [genarg] Fix Yojson serialization.

.github/workflows/ci.yml, coq-serapi.opam, sertop/sertop_js.ml
We use aptitude's better solver which seems to work and remove some
cruft libs that were giving us problems.
We also fix the Ubuntu version, hopefully this ends being more stable.
=> [ci] Fix 32bit gcc setup failure.

serlib/ser_constrexpr.ml, serlib/ser_constrexpr.mli, serlib/ser_vernacexpr.ml, serlib/ser_vernacexpr.mli
Adapt to https://github.com/coq/coq/pull/14928
=> Adapt to https://github.com/coq/coq/pull/14928

serlib/ser_declarations.ml, serlib/ser_declarations.mli, serlib/ser_entries.ml, serlib/ser_sorts.ml, serlib/ser_sorts.mli
I don't really know what I'm doing here, I just made it so that the code compiles
=> Adapt to coq/coq#18038 (rewrite rules)

CHANGES.md, serlib/plugins/extraction/dune, serlib/plugins/extraction/ser_g_extraction.ml, tests/genarg/dune, tests/genarg/extraction.v
=> Support the extraction plugin

CHANGES.md, serlib/ser_cPrimitives.ml, tests/genarg/dune, tests/genarg/primitives.v
That was a quite dumb TODO I forgot about. But indeed, GADT remain an issue for us.
Fixes #397 , fixes sr-lab/coqpyt#35
Thanks to Laetitia Teodorescu (@laetitia-teo) and Nuno Saavedra (@Nfsaavedra) for the bug report.
=> [serlib] Fix TODO / bug in primitive code.

serlib/plugins/ltac2/ser_tac2expr.ml, tests/genarg/dune, tests/genarg/ltac2.v
This broke in #18432, creating a segfault.
cc https://github.com/ejgallego/coq-serapi/issues/82
cc: @afdw
=> [serlib] [ltac2] Fix wrong piercing creating havoc.

serapi/serapi_protocol.ml, sertop/comp_common.ml, sertop/sertop_sexp.ml
Adapt to https://github.com/coq/coq/pull/19370
To be merged in sync with the upstream PR
=> Adapt to https://github.com/coq/coq/pull/19370
